### PR TITLE
Initial attempt at associations

### PR DESCRIPTION
**Pull request by kesne**

### CODE REVIEW

**Comment by Emily** [comment]
@kesne this just implements the types, not the actual query portion?

**Comment by kesne** [comment]
Correct this is just basic API sketch and trying to get the types to work correctly.

**Comment by Emily** [comment]
Seems reasonable to me. As for projecting, I wonder if we can find a way to put in the existing `pluck` -- maybe something with a map type? Or at least something like, `pluckAssociation('post', ['list', 'of', 'fields'])`?

**Comment by kesne** [comment]
Replacing with #16, which will handle all of this.

**Pull request closed without merging**
